# Generated by Django 5.2.7 on 2026-01-23 14:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library', '0006_book_disposition_alter_book_author'),
        ('users', '0003_selectedbook_subscribeauthor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selectedbook',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_books', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subscribeauthor',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='selectedbook',
            unique_together={('user', 'book')},
        ),
        migrations.AlterUniqueTogether(
            name='subscribeauthor',
            unique_together={('user', 'author')},
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=500, verbose_name='текст')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Коммент',
                'verbose_name_plural': 'Комменты',
            },
        ),
    ]
