# Generated by Django 5.2.7 on 2026-01-29 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_comment_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_tested',
            field=models.BooleanField(default=False, verbose_name='Прошел тест?'),
        ),
    ]
