# Generated by Django 5.2.7 on 2026-01-30 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_is_tested'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField()),
                ('comment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.comment')),
                ('selected_book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.selectedbook')),
                ('subscribe_author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.subscribeauthor')),
            ],
        ),
    ]
