# Generated by Django 5.2.7 on 2026-01-30 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library', '0006_book_disposition_alter_book_author'),
        ('users', '0009_scorelog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scorelog',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='scorelog',
            name='selected_book',
        ),
        migrations.RemoveField(
            model_name='scorelog',
            name='subscribe_author',
        ),
        migrations.AddField(
            model_name='scorelog',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='library.author'),
        ),
        migrations.AddField(
            model_name='scorelog',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='library.book'),
        ),
    ]
