# Generated by Django 5.2.7 on 2026-01-30 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_scorelog_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='scorelog',
            name='comment',
            field=models.BooleanField(default=False),
        ),
    ]
