upstream library_backend {
    server web:8000;
}

server {
    listen 80;

    # Игнорируем проблемы с размером загружаемых файлов (книги до 50МБ)
    client_max_body_size 100M;

    location / {
        proxy_pass http://library_backend;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;
        proxy_redirect off;
    }

    # Статику отдаем через Nginx
    location /static/ {
        alias /app/staticfiles/;
    }

    # Медиафайлы (включая тексты книг) тоже отдаем через Nginx
    location /media/ {
        alias /app/media/;
    }
}